version: '2'
services:
  priority_db:
    image: mongo
  priority_taskmanager:
    image: priority_taskmanager:1.0 
    ports:
      - "3000:3000"
    depends_on:
      - priority_db
    environment:
      -  HOST=priority_db
      -  MONGOPORT=27017
      - "affinity:container==*priority_db*"
